services:
  backend:
    build: ./server
    ports:
      - "80:80"
    volumes:
      - ./server/app:/code/app

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - backend
